[package]
name = "BuzzFlux"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.86"
tracing-subscriber = "0.3.18"
url = "2.5.2"
serde = { version = "1.0.208", features = ["derive"] }
toml = "0.8.19"